package com.xzs.pojo;

import java.util.Date;

public class TaskExamCustomerAnswer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_exam_customer_answer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_exam_customer_answer.task_exam_id
     *
     * @mbg.generated
     */
    private Integer taskExamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_exam_customer_answer.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_exam_customer_answer.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_exam_customer_answer.text_content_id
     *
     * @mbg.generated
     */
    private Integer textContentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam_customer_answer
     *
     * @mbg.generated
     */
    public TaskExamCustomerAnswer(Integer id, Integer taskExamId, Integer createUser, Date createTime, Integer textContentId) {
        this.id = id;
        this.taskExamId = taskExamId;
        this.createUser = createUser;
        this.createTime = createTime;
        this.textContentId = textContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam_customer_answer
     *
     * @mbg.generated
     */
    public TaskExamCustomerAnswer() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_exam_customer_answer.id
     *
     * @return the value of t_task_exam_customer_answer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_exam_customer_answer.id
     *
     * @param id the value for t_task_exam_customer_answer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_exam_customer_answer.task_exam_id
     *
     * @return the value of t_task_exam_customer_answer.task_exam_id
     *
     * @mbg.generated
     */
    public Integer getTaskExamId() {
        return taskExamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_exam_customer_answer.task_exam_id
     *
     * @param taskExamId the value for t_task_exam_customer_answer.task_exam_id
     *
     * @mbg.generated
     */
    public void setTaskExamId(Integer taskExamId) {
        this.taskExamId = taskExamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_exam_customer_answer.create_user
     *
     * @return the value of t_task_exam_customer_answer.create_user
     *
     * @mbg.generated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_exam_customer_answer.create_user
     *
     * @param createUser the value for t_task_exam_customer_answer.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_exam_customer_answer.create_time
     *
     * @return the value of t_task_exam_customer_answer.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_exam_customer_answer.create_time
     *
     * @param createTime the value for t_task_exam_customer_answer.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_exam_customer_answer.text_content_id
     *
     * @return the value of t_task_exam_customer_answer.text_content_id
     *
     * @mbg.generated
     */
    public Integer getTextContentId() {
        return textContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_exam_customer_answer.text_content_id
     *
     * @param textContentId the value for t_task_exam_customer_answer.text_content_id
     *
     * @mbg.generated
     */
    public void setTextContentId(Integer textContentId) {
        this.textContentId = textContentId;
    }
}