package com.xzs.pojo;

import com.baomidou.mybatisplus.annotation.TableField;

import java.util.Date;
import java.util.List;

public class TaskExam {
    @TableField (exist =  false)
    private  String conten;
    @TableField (exist =  false)
    private List<TexamPaper> paperItems;


    public List<TexamPaper> getPaperItems() {
        return paperItems;
    }

    public void setPaperItems(List<TexamPaper> paperItems) {
        this.paperItems = paperItems;
    }

    public String getConten() {
        return conten;
    }

    public void setConten(String conten) {
        this.conten = conten;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_exam.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_exam.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_exam.grade_level
     *
     * @mbg.generated
     */
    private Integer gradeLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_exam.frame_text_content_id
     *
     * @mbg.generated
     */
    private String frameTextContentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_exam.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_exam.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_exam.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_exam.create_user_name
     *
     * @mbg.generated
     */
    private String createUserName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam
     *
     * @mbg.generated
     */
    public TaskExam(Integer id, String title, Integer gradeLevel, String frameTextContentId, Integer createUser, Date createTime, Boolean deleted, String createUserName) {
        this.id = id;
        this.title = title;
        this.gradeLevel = gradeLevel;
        this.frameTextContentId = frameTextContentId;
        this.createUser = createUser;
        this.createTime = createTime;
        this.deleted = deleted;
        this.createUserName = createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam
     *
     * @mbg.generated
     */
    public TaskExam() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_exam.id
     *
     * @return the value of t_task_exam.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_exam.id
     *
     * @param id the value for t_task_exam.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_exam.title
     *
     * @return the value of t_task_exam.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_exam.title
     *
     * @param title the value for t_task_exam.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_exam.grade_level
     *
     * @return the value of t_task_exam.grade_level
     *
     * @mbg.generated
     */
    public Integer getGradeLevel() {
        return gradeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_exam.grade_level
     *
     * @param gradeLevel the value for t_task_exam.grade_level
     *
     * @mbg.generated
     */
    public void setGradeLevel(Integer gradeLevel) {
        this.gradeLevel = gradeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_exam.frame_text_content_id
     *
     * @return the value of t_task_exam.frame_text_content_id
     *
     * @mbg.generated
     */
    public String getFrameTextContentId() {
        return frameTextContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_exam.frame_text_content_id
     *
     * @param frameTextContentId the value for t_task_exam.frame_text_content_id
     *
     * @mbg.generated
     */
    public void setFrameTextContentId(String frameTextContentId) {
        this.frameTextContentId = frameTextContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_exam.create_user
     *
     * @return the value of t_task_exam.create_user
     *
     * @mbg.generated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_exam.create_user
     *
     * @param createUser the value for t_task_exam.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_exam.create_time
     *
     * @return the value of t_task_exam.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_exam.create_time
     *
     * @param createTime the value for t_task_exam.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_exam.deleted
     *
     * @return the value of t_task_exam.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_exam.deleted
     *
     * @param deleted the value for t_task_exam.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_exam.create_user_name
     *
     * @return the value of t_task_exam.create_user_name
     *
     * @mbg.generated
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_exam.create_user_name
     *
     * @param createUserName the value for t_task_exam.create_user_name
     *
     * @mbg.generated
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }
}