package com.xzs.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TexamPaperExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public TexamPaperExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIsNull() {
            addCriterion("subject_id is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIsNotNull() {
            addCriterion("subject_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdEqualTo(Integer value) {
            addCriterion("subject_id =", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotEqualTo(Integer value) {
            addCriterion("subject_id <>", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdGreaterThan(Integer value) {
            addCriterion("subject_id >", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("subject_id >=", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdLessThan(Integer value) {
            addCriterion("subject_id <", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("subject_id <=", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIn(List<Integer> values) {
            addCriterion("subject_id in", values, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotIn(List<Integer> values) {
            addCriterion("subject_id not in", values, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdBetween(Integer value1, Integer value2) {
            addCriterion("subject_id between", value1, value2, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("subject_id not between", value1, value2, "subjectId");
            return (Criteria) this;
        }

        public Criteria andPaperTypeIsNull() {
            addCriterion("paper_type is null");
            return (Criteria) this;
        }

        public Criteria andPaperTypeIsNotNull() {
            addCriterion("paper_type is not null");
            return (Criteria) this;
        }

        public Criteria andPaperTypeEqualTo(Integer value) {
            addCriterion("paper_type =", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeNotEqualTo(Integer value) {
            addCriterion("paper_type <>", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeGreaterThan(Integer value) {
            addCriterion("paper_type >", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("paper_type >=", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeLessThan(Integer value) {
            addCriterion("paper_type <", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeLessThanOrEqualTo(Integer value) {
            addCriterion("paper_type <=", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeIn(List<Integer> values) {
            addCriterion("paper_type in", values, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeNotIn(List<Integer> values) {
            addCriterion("paper_type not in", values, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeBetween(Integer value1, Integer value2) {
            addCriterion("paper_type between", value1, value2, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("paper_type not between", value1, value2, "paperType");
            return (Criteria) this;
        }

        public Criteria andGradeLevelIsNull() {
            addCriterion("grade_level is null");
            return (Criteria) this;
        }

        public Criteria andGradeLevelIsNotNull() {
            addCriterion("grade_level is not null");
            return (Criteria) this;
        }

        public Criteria andGradeLevelEqualTo(Integer value) {
            addCriterion("grade_level =", value, "gradeLevel");
            return (Criteria) this;
        }

        public Criteria andGradeLevelNotEqualTo(Integer value) {
            addCriterion("grade_level <>", value, "gradeLevel");
            return (Criteria) this;
        }

        public Criteria andGradeLevelGreaterThan(Integer value) {
            addCriterion("grade_level >", value, "gradeLevel");
            return (Criteria) this;
        }

        public Criteria andGradeLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("grade_level >=", value, "gradeLevel");
            return (Criteria) this;
        }

        public Criteria andGradeLevelLessThan(Integer value) {
            addCriterion("grade_level <", value, "gradeLevel");
            return (Criteria) this;
        }

        public Criteria andGradeLevelLessThanOrEqualTo(Integer value) {
            addCriterion("grade_level <=", value, "gradeLevel");
            return (Criteria) this;
        }

        public Criteria andGradeLevelIn(List<Integer> values) {
            addCriterion("grade_level in", values, "gradeLevel");
            return (Criteria) this;
        }

        public Criteria andGradeLevelNotIn(List<Integer> values) {
            addCriterion("grade_level not in", values, "gradeLevel");
            return (Criteria) this;
        }

        public Criteria andGradeLevelBetween(Integer value1, Integer value2) {
            addCriterion("grade_level between", value1, value2, "gradeLevel");
            return (Criteria) this;
        }

        public Criteria andGradeLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("grade_level not between", value1, value2, "gradeLevel");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(Integer value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(Integer value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(Integer value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(Integer value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(Integer value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<Integer> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<Integer> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(Integer value1, Integer value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andQuestionCountIsNull() {
            addCriterion("question_count is null");
            return (Criteria) this;
        }

        public Criteria andQuestionCountIsNotNull() {
            addCriterion("question_count is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionCountEqualTo(Integer value) {
            addCriterion("question_count =", value, "questionCount");
            return (Criteria) this;
        }

        public Criteria andQuestionCountNotEqualTo(Integer value) {
            addCriterion("question_count <>", value, "questionCount");
            return (Criteria) this;
        }

        public Criteria andQuestionCountGreaterThan(Integer value) {
            addCriterion("question_count >", value, "questionCount");
            return (Criteria) this;
        }

        public Criteria andQuestionCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("question_count >=", value, "questionCount");
            return (Criteria) this;
        }

        public Criteria andQuestionCountLessThan(Integer value) {
            addCriterion("question_count <", value, "questionCount");
            return (Criteria) this;
        }

        public Criteria andQuestionCountLessThanOrEqualTo(Integer value) {
            addCriterion("question_count <=", value, "questionCount");
            return (Criteria) this;
        }

        public Criteria andQuestionCountIn(List<Integer> values) {
            addCriterion("question_count in", values, "questionCount");
            return (Criteria) this;
        }

        public Criteria andQuestionCountNotIn(List<Integer> values) {
            addCriterion("question_count not in", values, "questionCount");
            return (Criteria) this;
        }

        public Criteria andQuestionCountBetween(Integer value1, Integer value2) {
            addCriterion("question_count between", value1, value2, "questionCount");
            return (Criteria) this;
        }

        public Criteria andQuestionCountNotBetween(Integer value1, Integer value2) {
            addCriterion("question_count not between", value1, value2, "questionCount");
            return (Criteria) this;
        }

        public Criteria andSuggestTimeIsNull() {
            addCriterion("suggest_time is null");
            return (Criteria) this;
        }

        public Criteria andSuggestTimeIsNotNull() {
            addCriterion("suggest_time is not null");
            return (Criteria) this;
        }

        public Criteria andSuggestTimeEqualTo(Integer value) {
            addCriterion("suggest_time =", value, "suggestTime");
            return (Criteria) this;
        }

        public Criteria andSuggestTimeNotEqualTo(Integer value) {
            addCriterion("suggest_time <>", value, "suggestTime");
            return (Criteria) this;
        }

        public Criteria andSuggestTimeGreaterThan(Integer value) {
            addCriterion("suggest_time >", value, "suggestTime");
            return (Criteria) this;
        }

        public Criteria andSuggestTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("suggest_time >=", value, "suggestTime");
            return (Criteria) this;
        }

        public Criteria andSuggestTimeLessThan(Integer value) {
            addCriterion("suggest_time <", value, "suggestTime");
            return (Criteria) this;
        }

        public Criteria andSuggestTimeLessThanOrEqualTo(Integer value) {
            addCriterion("suggest_time <=", value, "suggestTime");
            return (Criteria) this;
        }

        public Criteria andSuggestTimeIn(List<Integer> values) {
            addCriterion("suggest_time in", values, "suggestTime");
            return (Criteria) this;
        }

        public Criteria andSuggestTimeNotIn(List<Integer> values) {
            addCriterion("suggest_time not in", values, "suggestTime");
            return (Criteria) this;
        }

        public Criteria andSuggestTimeBetween(Integer value1, Integer value2) {
            addCriterion("suggest_time between", value1, value2, "suggestTime");
            return (Criteria) this;
        }

        public Criteria andSuggestTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("suggest_time not between", value1, value2, "suggestTime");
            return (Criteria) this;
        }

        public Criteria andLimitStartTimeIsNull() {
            addCriterion("limit_start_time is null");
            return (Criteria) this;
        }

        public Criteria andLimitStartTimeIsNotNull() {
            addCriterion("limit_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andLimitStartTimeEqualTo(Date value) {
            addCriterion("limit_start_time =", value, "limitStartTime");
            return (Criteria) this;
        }

        public Criteria andLimitStartTimeNotEqualTo(Date value) {
            addCriterion("limit_start_time <>", value, "limitStartTime");
            return (Criteria) this;
        }

        public Criteria andLimitStartTimeGreaterThan(Date value) {
            addCriterion("limit_start_time >", value, "limitStartTime");
            return (Criteria) this;
        }

        public Criteria andLimitStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("limit_start_time >=", value, "limitStartTime");
            return (Criteria) this;
        }

        public Criteria andLimitStartTimeLessThan(Date value) {
            addCriterion("limit_start_time <", value, "limitStartTime");
            return (Criteria) this;
        }

        public Criteria andLimitStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("limit_start_time <=", value, "limitStartTime");
            return (Criteria) this;
        }

        public Criteria andLimitStartTimeIn(List<Date> values) {
            addCriterion("limit_start_time in", values, "limitStartTime");
            return (Criteria) this;
        }

        public Criteria andLimitStartTimeNotIn(List<Date> values) {
            addCriterion("limit_start_time not in", values, "limitStartTime");
            return (Criteria) this;
        }

        public Criteria andLimitStartTimeBetween(Date value1, Date value2) {
            addCriterion("limit_start_time between", value1, value2, "limitStartTime");
            return (Criteria) this;
        }

        public Criteria andLimitStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("limit_start_time not between", value1, value2, "limitStartTime");
            return (Criteria) this;
        }

        public Criteria andLimitEndTimeIsNull() {
            addCriterion("limit_end_time is null");
            return (Criteria) this;
        }

        public Criteria andLimitEndTimeIsNotNull() {
            addCriterion("limit_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andLimitEndTimeEqualTo(Date value) {
            addCriterion("limit_end_time =", value, "limitEndTime");
            return (Criteria) this;
        }

        public Criteria andLimitEndTimeNotEqualTo(Date value) {
            addCriterion("limit_end_time <>", value, "limitEndTime");
            return (Criteria) this;
        }

        public Criteria andLimitEndTimeGreaterThan(Date value) {
            addCriterion("limit_end_time >", value, "limitEndTime");
            return (Criteria) this;
        }

        public Criteria andLimitEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("limit_end_time >=", value, "limitEndTime");
            return (Criteria) this;
        }

        public Criteria andLimitEndTimeLessThan(Date value) {
            addCriterion("limit_end_time <", value, "limitEndTime");
            return (Criteria) this;
        }

        public Criteria andLimitEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("limit_end_time <=", value, "limitEndTime");
            return (Criteria) this;
        }

        public Criteria andLimitEndTimeIn(List<Date> values) {
            addCriterion("limit_end_time in", values, "limitEndTime");
            return (Criteria) this;
        }

        public Criteria andLimitEndTimeNotIn(List<Date> values) {
            addCriterion("limit_end_time not in", values, "limitEndTime");
            return (Criteria) this;
        }

        public Criteria andLimitEndTimeBetween(Date value1, Date value2) {
            addCriterion("limit_end_time between", value1, value2, "limitEndTime");
            return (Criteria) this;
        }

        public Criteria andLimitEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("limit_end_time not between", value1, value2, "limitEndTime");
            return (Criteria) this;
        }

        public Criteria andFrameTextContentIdIsNull() {
            addCriterion("frame_text_content_id is null");
            return (Criteria) this;
        }

        public Criteria andFrameTextContentIdIsNotNull() {
            addCriterion("frame_text_content_id is not null");
            return (Criteria) this;
        }

        public Criteria andFrameTextContentIdEqualTo(Integer value) {
            addCriterion("frame_text_content_id =", value, "frameTextContentId");
            return (Criteria) this;
        }

        public Criteria andFrameTextContentIdNotEqualTo(Integer value) {
            addCriterion("frame_text_content_id <>", value, "frameTextContentId");
            return (Criteria) this;
        }

        public Criteria andFrameTextContentIdGreaterThan(Integer value) {
            addCriterion("frame_text_content_id >", value, "frameTextContentId");
            return (Criteria) this;
        }

        public Criteria andFrameTextContentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("frame_text_content_id >=", value, "frameTextContentId");
            return (Criteria) this;
        }

        public Criteria andFrameTextContentIdLessThan(Integer value) {
            addCriterion("frame_text_content_id <", value, "frameTextContentId");
            return (Criteria) this;
        }

        public Criteria andFrameTextContentIdLessThanOrEqualTo(Integer value) {
            addCriterion("frame_text_content_id <=", value, "frameTextContentId");
            return (Criteria) this;
        }

        public Criteria andFrameTextContentIdIn(List<Integer> values) {
            addCriterion("frame_text_content_id in", values, "frameTextContentId");
            return (Criteria) this;
        }

        public Criteria andFrameTextContentIdNotIn(List<Integer> values) {
            addCriterion("frame_text_content_id not in", values, "frameTextContentId");
            return (Criteria) this;
        }

        public Criteria andFrameTextContentIdBetween(Integer value1, Integer value2) {
            addCriterion("frame_text_content_id between", value1, value2, "frameTextContentId");
            return (Criteria) this;
        }

        public Criteria andFrameTextContentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("frame_text_content_id not between", value1, value2, "frameTextContentId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(Integer value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(Integer value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(Integer value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(Integer value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(Integer value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<Integer> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<Integer> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(Integer value1, Integer value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Boolean value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andTaskExamIdIsNull() {
            addCriterion("task_exam_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskExamIdIsNotNull() {
            addCriterion("task_exam_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskExamIdEqualTo(Integer value) {
            addCriterion("task_exam_id =", value, "taskExamId");
            return (Criteria) this;
        }

        public Criteria andTaskExamIdNotEqualTo(Integer value) {
            addCriterion("task_exam_id <>", value, "taskExamId");
            return (Criteria) this;
        }

        public Criteria andTaskExamIdGreaterThan(Integer value) {
            addCriterion("task_exam_id >", value, "taskExamId");
            return (Criteria) this;
        }

        public Criteria andTaskExamIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("task_exam_id >=", value, "taskExamId");
            return (Criteria) this;
        }

        public Criteria andTaskExamIdLessThan(Integer value) {
            addCriterion("task_exam_id <", value, "taskExamId");
            return (Criteria) this;
        }

        public Criteria andTaskExamIdLessThanOrEqualTo(Integer value) {
            addCriterion("task_exam_id <=", value, "taskExamId");
            return (Criteria) this;
        }

        public Criteria andTaskExamIdIn(List<Integer> values) {
            addCriterion("task_exam_id in", values, "taskExamId");
            return (Criteria) this;
        }

        public Criteria andTaskExamIdNotIn(List<Integer> values) {
            addCriterion("task_exam_id not in", values, "taskExamId");
            return (Criteria) this;
        }

        public Criteria andTaskExamIdBetween(Integer value1, Integer value2) {
            addCriterion("task_exam_id between", value1, value2, "taskExamId");
            return (Criteria) this;
        }

        public Criteria andTaskExamIdNotBetween(Integer value1, Integer value2) {
            addCriterion("task_exam_id not between", value1, value2, "taskExamId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_exam_paper
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}