package com.xzs.pojo;

import java.util.Date;

public class TexamPaperAnswer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_answer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_answer.exam_paper_id
     *
     * @mbg.generated
     */
    private Integer examPaperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_answer.paper_name
     *
     * @mbg.generated
     */
    private String paperName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_answer.paper_type
     *
     * @mbg.generated
     */
    private Integer paperType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_answer.subject_id
     *
     * @mbg.generated
     */
    private Integer subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_answer.system_score
     *
     * @mbg.generated
     */
    private Integer systemScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_answer.user_score
     *
     * @mbg.generated
     */
    private Integer userScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_answer.paper_score
     *
     * @mbg.generated
     */
    private Integer paperScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_answer.question_correct
     *
     * @mbg.generated
     */
    private Integer questionCorrect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_answer.question_count
     *
     * @mbg.generated
     */
    private Integer questionCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_answer.do_time
     *
     * @mbg.generated
     */
    private Integer doTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_answer.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_answer.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_answer.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_answer.task_exam_id
     *
     * @mbg.generated
     */
    private Integer taskExamId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper_answer
     *
     * @mbg.generated
     */
    public TexamPaperAnswer(Integer id, Integer examPaperId, String paperName, Integer paperType, Integer subjectId, Integer systemScore, Integer userScore, Integer paperScore, Integer questionCorrect, Integer questionCount, Integer doTime, Integer status, Integer createUser, Date createTime, Integer taskExamId) {
        this.id = id;
        this.examPaperId = examPaperId;
        this.paperName = paperName;
        this.paperType = paperType;
        this.subjectId = subjectId;
        this.systemScore = systemScore;
        this.userScore = userScore;
        this.paperScore = paperScore;
        this.questionCorrect = questionCorrect;
        this.questionCount = questionCount;
        this.doTime = doTime;
        this.status = status;
        this.createUser = createUser;
        this.createTime = createTime;
        this.taskExamId = taskExamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper_answer
     *
     * @mbg.generated
     */
    public TexamPaperAnswer() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_answer.id
     *
     * @return the value of t_exam_paper_answer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_answer.id
     *
     * @param id the value for t_exam_paper_answer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_answer.exam_paper_id
     *
     * @return the value of t_exam_paper_answer.exam_paper_id
     *
     * @mbg.generated
     */
    public Integer getExamPaperId() {
        return examPaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_answer.exam_paper_id
     *
     * @param examPaperId the value for t_exam_paper_answer.exam_paper_id
     *
     * @mbg.generated
     */
    public void setExamPaperId(Integer examPaperId) {
        this.examPaperId = examPaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_answer.paper_name
     *
     * @return the value of t_exam_paper_answer.paper_name
     *
     * @mbg.generated
     */
    public String getPaperName() {
        return paperName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_answer.paper_name
     *
     * @param paperName the value for t_exam_paper_answer.paper_name
     *
     * @mbg.generated
     */
    public void setPaperName(String paperName) {
        this.paperName = paperName == null ? null : paperName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_answer.paper_type
     *
     * @return the value of t_exam_paper_answer.paper_type
     *
     * @mbg.generated
     */
    public Integer getPaperType() {
        return paperType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_answer.paper_type
     *
     * @param paperType the value for t_exam_paper_answer.paper_type
     *
     * @mbg.generated
     */
    public void setPaperType(Integer paperType) {
        this.paperType = paperType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_answer.subject_id
     *
     * @return the value of t_exam_paper_answer.subject_id
     *
     * @mbg.generated
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_answer.subject_id
     *
     * @param subjectId the value for t_exam_paper_answer.subject_id
     *
     * @mbg.generated
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_answer.system_score
     *
     * @return the value of t_exam_paper_answer.system_score
     *
     * @mbg.generated
     */
    public Integer getSystemScore() {
        return systemScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_answer.system_score
     *
     * @param systemScore the value for t_exam_paper_answer.system_score
     *
     * @mbg.generated
     */
    public void setSystemScore(Integer systemScore) {
        this.systemScore = systemScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_answer.user_score
     *
     * @return the value of t_exam_paper_answer.user_score
     *
     * @mbg.generated
     */
    public Integer getUserScore() {
        return userScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_answer.user_score
     *
     * @param userScore the value for t_exam_paper_answer.user_score
     *
     * @mbg.generated
     */
    public void setUserScore(Integer userScore) {
        this.userScore = userScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_answer.paper_score
     *
     * @return the value of t_exam_paper_answer.paper_score
     *
     * @mbg.generated
     */
    public Integer getPaperScore() {
        return paperScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_answer.paper_score
     *
     * @param paperScore the value for t_exam_paper_answer.paper_score
     *
     * @mbg.generated
     */
    public void setPaperScore(Integer paperScore) {
        this.paperScore = paperScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_answer.question_correct
     *
     * @return the value of t_exam_paper_answer.question_correct
     *
     * @mbg.generated
     */
    public Integer getQuestionCorrect() {
        return questionCorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_answer.question_correct
     *
     * @param questionCorrect the value for t_exam_paper_answer.question_correct
     *
     * @mbg.generated
     */
    public void setQuestionCorrect(Integer questionCorrect) {
        this.questionCorrect = questionCorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_answer.question_count
     *
     * @return the value of t_exam_paper_answer.question_count
     *
     * @mbg.generated
     */
    public Integer getQuestionCount() {
        return questionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_answer.question_count
     *
     * @param questionCount the value for t_exam_paper_answer.question_count
     *
     * @mbg.generated
     */
    public void setQuestionCount(Integer questionCount) {
        this.questionCount = questionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_answer.do_time
     *
     * @return the value of t_exam_paper_answer.do_time
     *
     * @mbg.generated
     */
    public Integer getDoTime() {
        return doTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_answer.do_time
     *
     * @param doTime the value for t_exam_paper_answer.do_time
     *
     * @mbg.generated
     */
    public void setDoTime(Integer doTime) {
        this.doTime = doTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_answer.status
     *
     * @return the value of t_exam_paper_answer.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_answer.status
     *
     * @param status the value for t_exam_paper_answer.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_answer.create_user
     *
     * @return the value of t_exam_paper_answer.create_user
     *
     * @mbg.generated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_answer.create_user
     *
     * @param createUser the value for t_exam_paper_answer.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_answer.create_time
     *
     * @return the value of t_exam_paper_answer.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_answer.create_time
     *
     * @param createTime the value for t_exam_paper_answer.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_answer.task_exam_id
     *
     * @return the value of t_exam_paper_answer.task_exam_id
     *
     * @mbg.generated
     */
    public Integer getTaskExamId() {
        return taskExamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_answer.task_exam_id
     *
     * @param taskExamId the value for t_exam_paper_answer.task_exam_id
     *
     * @mbg.generated
     */
    public void setTaskExamId(Integer taskExamId) {
        this.taskExamId = taskExamId;
    }
}