package com.xzs.pojo;

import java.util.Date;

public class TExam_paperQuestionCustomerAnswer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_question_customer_answer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_question_customer_answer.question_id
     *
     * @mbg.generated
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_question_customer_answer.exam_paper_id
     *
     * @mbg.generated
     */
    private Integer examPaperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_question_customer_answer.exam_paper_answer_id
     *
     * @mbg.generated
     */
    private Integer examPaperAnswerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_question_customer_answer.question_type
     *
     * @mbg.generated
     */
    private Integer questionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_question_customer_answer.subject_id
     *
     * @mbg.generated
     */
    private Integer subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_question_customer_answer.customer_score
     *
     * @mbg.generated
     */
    private Integer customerScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_question_customer_answer.question_score
     *
     * @mbg.generated
     */
    private Integer questionScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_question_customer_answer.question_text_content_id
     *
     * @mbg.generated
     */
    private Integer questionTextContentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_question_customer_answer.answer
     *
     * @mbg.generated
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_question_customer_answer.text_content_id
     *
     * @mbg.generated
     */
    private Integer textContentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_question_customer_answer.do_right
     *
     * @mbg.generated
     */
    private Boolean doRight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_question_customer_answer.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_question_customer_answer.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper_question_customer_answer.item_order
     *
     * @mbg.generated
     */
    private Integer itemOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper_question_customer_answer
     *
     * @mbg.generated
     */
    public TExam_paperQuestionCustomerAnswer(Integer id, Integer questionId, Integer examPaperId, Integer examPaperAnswerId, Integer questionType, Integer subjectId, Integer customerScore, Integer questionScore, Integer questionTextContentId, String answer, Integer textContentId, Boolean doRight, Integer createUser, Date createTime, Integer itemOrder) {
        this.id = id;
        this.questionId = questionId;
        this.examPaperId = examPaperId;
        this.examPaperAnswerId = examPaperAnswerId;
        this.questionType = questionType;
        this.subjectId = subjectId;
        this.customerScore = customerScore;
        this.questionScore = questionScore;
        this.questionTextContentId = questionTextContentId;
        this.answer = answer;
        this.textContentId = textContentId;
        this.doRight = doRight;
        this.createUser = createUser;
        this.createTime = createTime;
        this.itemOrder = itemOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper_question_customer_answer
     *
     * @mbg.generated
     */
    public TExam_paperQuestionCustomerAnswer() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_question_customer_answer.id
     *
     * @return the value of t_exam_paper_question_customer_answer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_question_customer_answer.id
     *
     * @param id the value for t_exam_paper_question_customer_answer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_question_customer_answer.question_id
     *
     * @return the value of t_exam_paper_question_customer_answer.question_id
     *
     * @mbg.generated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_question_customer_answer.question_id
     *
     * @param questionId the value for t_exam_paper_question_customer_answer.question_id
     *
     * @mbg.generated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_question_customer_answer.exam_paper_id
     *
     * @return the value of t_exam_paper_question_customer_answer.exam_paper_id
     *
     * @mbg.generated
     */
    public Integer getExamPaperId() {
        return examPaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_question_customer_answer.exam_paper_id
     *
     * @param examPaperId the value for t_exam_paper_question_customer_answer.exam_paper_id
     *
     * @mbg.generated
     */
    public void setExamPaperId(Integer examPaperId) {
        this.examPaperId = examPaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_question_customer_answer.exam_paper_answer_id
     *
     * @return the value of t_exam_paper_question_customer_answer.exam_paper_answer_id
     *
     * @mbg.generated
     */
    public Integer getExamPaperAnswerId() {
        return examPaperAnswerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_question_customer_answer.exam_paper_answer_id
     *
     * @param examPaperAnswerId the value for t_exam_paper_question_customer_answer.exam_paper_answer_id
     *
     * @mbg.generated
     */
    public void setExamPaperAnswerId(Integer examPaperAnswerId) {
        this.examPaperAnswerId = examPaperAnswerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_question_customer_answer.question_type
     *
     * @return the value of t_exam_paper_question_customer_answer.question_type
     *
     * @mbg.generated
     */
    public Integer getQuestionType() {
        return questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_question_customer_answer.question_type
     *
     * @param questionType the value for t_exam_paper_question_customer_answer.question_type
     *
     * @mbg.generated
     */
    public void setQuestionType(Integer questionType) {
        this.questionType = questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_question_customer_answer.subject_id
     *
     * @return the value of t_exam_paper_question_customer_answer.subject_id
     *
     * @mbg.generated
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_question_customer_answer.subject_id
     *
     * @param subjectId the value for t_exam_paper_question_customer_answer.subject_id
     *
     * @mbg.generated
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_question_customer_answer.customer_score
     *
     * @return the value of t_exam_paper_question_customer_answer.customer_score
     *
     * @mbg.generated
     */
    public Integer getCustomerScore() {
        return customerScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_question_customer_answer.customer_score
     *
     * @param customerScore the value for t_exam_paper_question_customer_answer.customer_score
     *
     * @mbg.generated
     */
    public void setCustomerScore(Integer customerScore) {
        this.customerScore = customerScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_question_customer_answer.question_score
     *
     * @return the value of t_exam_paper_question_customer_answer.question_score
     *
     * @mbg.generated
     */
    public Integer getQuestionScore() {
        return questionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_question_customer_answer.question_score
     *
     * @param questionScore the value for t_exam_paper_question_customer_answer.question_score
     *
     * @mbg.generated
     */
    public void setQuestionScore(Integer questionScore) {
        this.questionScore = questionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_question_customer_answer.question_text_content_id
     *
     * @return the value of t_exam_paper_question_customer_answer.question_text_content_id
     *
     * @mbg.generated
     */
    public Integer getQuestionTextContentId() {
        return questionTextContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_question_customer_answer.question_text_content_id
     *
     * @param questionTextContentId the value for t_exam_paper_question_customer_answer.question_text_content_id
     *
     * @mbg.generated
     */
    public void setQuestionTextContentId(Integer questionTextContentId) {
        this.questionTextContentId = questionTextContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_question_customer_answer.answer
     *
     * @return the value of t_exam_paper_question_customer_answer.answer
     *
     * @mbg.generated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_question_customer_answer.answer
     *
     * @param answer the value for t_exam_paper_question_customer_answer.answer
     *
     * @mbg.generated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_question_customer_answer.text_content_id
     *
     * @return the value of t_exam_paper_question_customer_answer.text_content_id
     *
     * @mbg.generated
     */
    public Integer getTextContentId() {
        return textContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_question_customer_answer.text_content_id
     *
     * @param textContentId the value for t_exam_paper_question_customer_answer.text_content_id
     *
     * @mbg.generated
     */
    public void setTextContentId(Integer textContentId) {
        this.textContentId = textContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_question_customer_answer.do_right
     *
     * @return the value of t_exam_paper_question_customer_answer.do_right
     *
     * @mbg.generated
     */
    public Boolean getDoRight() {
        return doRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_question_customer_answer.do_right
     *
     * @param doRight the value for t_exam_paper_question_customer_answer.do_right
     *
     * @mbg.generated
     */
    public void setDoRight(Boolean doRight) {
        this.doRight = doRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_question_customer_answer.create_user
     *
     * @return the value of t_exam_paper_question_customer_answer.create_user
     *
     * @mbg.generated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_question_customer_answer.create_user
     *
     * @param createUser the value for t_exam_paper_question_customer_answer.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_question_customer_answer.create_time
     *
     * @return the value of t_exam_paper_question_customer_answer.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_question_customer_answer.create_time
     *
     * @param createTime the value for t_exam_paper_question_customer_answer.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper_question_customer_answer.item_order
     *
     * @return the value of t_exam_paper_question_customer_answer.item_order
     *
     * @mbg.generated
     */
    public Integer getItemOrder() {
        return itemOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper_question_customer_answer.item_order
     *
     * @param itemOrder the value for t_exam_paper_question_customer_answer.item_order
     *
     * @mbg.generated
     */
    public void setItemOrder(Integer itemOrder) {
        this.itemOrder = itemOrder;
    }
}