package com.xzs.pojo;

import java.util.Date;

public class TexamPaper {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.subject_id
     *
     * @mbg.generated
     */
    private Integer subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.paper_type
     *
     * @mbg.generated
     */
    private Integer paperType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.grade_level
     *
     * @mbg.generated
     */
    private Integer gradeLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.question_count
     *
     * @mbg.generated
     */
    private Integer questionCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.suggest_time
     *
     * @mbg.generated
     */
    private Integer suggestTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.limit_start_time
     *
     * @mbg.generated
     */
    private Date limitStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.limit_end_time
     *
     * @mbg.generated
     */
    private Date limitEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.frame_text_content_id
     *
     * @mbg.generated
     */
    private Integer frameTextContentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exam_paper.task_exam_id
     *
     * @mbg.generated
     */
    private Integer taskExamId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public TexamPaper(Integer id, String name, Integer subjectId, Integer paperType, Integer gradeLevel, Integer score, Integer questionCount, Integer suggestTime, Date limitStartTime, Date limitEndTime, Integer frameTextContentId, Integer createUser, Date createTime, Boolean deleted, Integer taskExamId) {
        this.id = id;
        this.name = name;
        this.subjectId = subjectId;
        this.paperType = paperType;
        this.gradeLevel = gradeLevel;
        this.score = score;
        this.questionCount = questionCount;
        this.suggestTime = suggestTime;
        this.limitStartTime = limitStartTime;
        this.limitEndTime = limitEndTime;
        this.frameTextContentId = frameTextContentId;
        this.createUser = createUser;
        this.createTime = createTime;
        this.deleted = deleted;
        this.taskExamId = taskExamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    public TexamPaper() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.id
     *
     * @return the value of t_exam_paper.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.id
     *
     * @param id the value for t_exam_paper.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.name
     *
     * @return the value of t_exam_paper.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.name
     *
     * @param name the value for t_exam_paper.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.subject_id
     *
     * @return the value of t_exam_paper.subject_id
     *
     * @mbg.generated
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.subject_id
     *
     * @param subjectId the value for t_exam_paper.subject_id
     *
     * @mbg.generated
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.paper_type
     *
     * @return the value of t_exam_paper.paper_type
     *
     * @mbg.generated
     */
    public Integer getPaperType() {
        return paperType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.paper_type
     *
     * @param paperType the value for t_exam_paper.paper_type
     *
     * @mbg.generated
     */
    public void setPaperType(Integer paperType) {
        this.paperType = paperType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.grade_level
     *
     * @return the value of t_exam_paper.grade_level
     *
     * @mbg.generated
     */
    public Integer getGradeLevel() {
        return gradeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.grade_level
     *
     * @param gradeLevel the value for t_exam_paper.grade_level
     *
     * @mbg.generated
     */
    public void setGradeLevel(Integer gradeLevel) {
        this.gradeLevel = gradeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.score
     *
     * @return the value of t_exam_paper.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.score
     *
     * @param score the value for t_exam_paper.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.question_count
     *
     * @return the value of t_exam_paper.question_count
     *
     * @mbg.generated
     */
    public Integer getQuestionCount() {
        return questionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.question_count
     *
     * @param questionCount the value for t_exam_paper.question_count
     *
     * @mbg.generated
     */
    public void setQuestionCount(Integer questionCount) {
        this.questionCount = questionCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.suggest_time
     *
     * @return the value of t_exam_paper.suggest_time
     *
     * @mbg.generated
     */
    public Integer getSuggestTime() {
        return suggestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.suggest_time
     *
     * @param suggestTime the value for t_exam_paper.suggest_time
     *
     * @mbg.generated
     */
    public void setSuggestTime(Integer suggestTime) {
        this.suggestTime = suggestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.limit_start_time
     *
     * @return the value of t_exam_paper.limit_start_time
     *
     * @mbg.generated
     */
    public Date getLimitStartTime() {
        return limitStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.limit_start_time
     *
     * @param limitStartTime the value for t_exam_paper.limit_start_time
     *
     * @mbg.generated
     */
    public void setLimitStartTime(Date limitStartTime) {
        this.limitStartTime = limitStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.limit_end_time
     *
     * @return the value of t_exam_paper.limit_end_time
     *
     * @mbg.generated
     */
    public Date getLimitEndTime() {
        return limitEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.limit_end_time
     *
     * @param limitEndTime the value for t_exam_paper.limit_end_time
     *
     * @mbg.generated
     */
    public void setLimitEndTime(Date limitEndTime) {
        this.limitEndTime = limitEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.frame_text_content_id
     *
     * @return the value of t_exam_paper.frame_text_content_id
     *
     * @mbg.generated
     */
    public Integer getFrameTextContentId() {
        return frameTextContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.frame_text_content_id
     *
     * @param frameTextContentId the value for t_exam_paper.frame_text_content_id
     *
     * @mbg.generated
     */
    public void setFrameTextContentId(Integer frameTextContentId) {
        this.frameTextContentId = frameTextContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.create_user
     *
     * @return the value of t_exam_paper.create_user
     *
     * @mbg.generated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.create_user
     *
     * @param createUser the value for t_exam_paper.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.create_time
     *
     * @return the value of t_exam_paper.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.create_time
     *
     * @param createTime the value for t_exam_paper.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.deleted
     *
     * @return the value of t_exam_paper.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.deleted
     *
     * @param deleted the value for t_exam_paper.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exam_paper.task_exam_id
     *
     * @return the value of t_exam_paper.task_exam_id
     *
     * @mbg.generated
     */
    public Integer getTaskExamId() {
        return taskExamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exam_paper.task_exam_id
     *
     * @param taskExamId the value for t_exam_paper.task_exam_id
     *
     * @mbg.generated
     */
    public void setTaskExamId(Integer taskExamId) {
        this.taskExamId = taskExamId;
    }
}