package com.xzs.pojo;

import java.util.Date;

public class Tmessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.send_user_id
     *
     * @mbg.generated
     */
    private Integer sendUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.send_user_name
     *
     * @mbg.generated
     */
    private String sendUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.send_real_name
     *
     * @mbg.generated
     */
    private String sendRealName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.receive_user_count
     *
     * @mbg.generated
     */
    private Integer receiveUserCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.read_count
     *
     * @mbg.generated
     */
    private Integer readCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated
     */
    public Tmessage(Integer id, String title, String content, Date createTime, Integer sendUserId, String sendUserName, String sendRealName, Integer receiveUserCount, Integer readCount) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.createTime = createTime;
        this.sendUserId = sendUserId;
        this.sendUserName = sendUserName;
        this.sendRealName = sendRealName;
        this.receiveUserCount = receiveUserCount;
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated
     */
    public Tmessage() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.id
     *
     * @return the value of t_message.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.id
     *
     * @param id the value for t_message.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.title
     *
     * @return the value of t_message.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.title
     *
     * @param title the value for t_message.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.content
     *
     * @return the value of t_message.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.content
     *
     * @param content the value for t_message.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.create_time
     *
     * @return the value of t_message.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.create_time
     *
     * @param createTime the value for t_message.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.send_user_id
     *
     * @return the value of t_message.send_user_id
     *
     * @mbg.generated
     */
    public Integer getSendUserId() {
        return sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.send_user_id
     *
     * @param sendUserId the value for t_message.send_user_id
     *
     * @mbg.generated
     */
    public void setSendUserId(Integer sendUserId) {
        this.sendUserId = sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.send_user_name
     *
     * @return the value of t_message.send_user_name
     *
     * @mbg.generated
     */
    public String getSendUserName() {
        return sendUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.send_user_name
     *
     * @param sendUserName the value for t_message.send_user_name
     *
     * @mbg.generated
     */
    public void setSendUserName(String sendUserName) {
        this.sendUserName = sendUserName == null ? null : sendUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.send_real_name
     *
     * @return the value of t_message.send_real_name
     *
     * @mbg.generated
     */
    public String getSendRealName() {
        return sendRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.send_real_name
     *
     * @param sendRealName the value for t_message.send_real_name
     *
     * @mbg.generated
     */
    public void setSendRealName(String sendRealName) {
        this.sendRealName = sendRealName == null ? null : sendRealName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.receive_user_count
     *
     * @return the value of t_message.receive_user_count
     *
     * @mbg.generated
     */
    public Integer getReceiveUserCount() {
        return receiveUserCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.receive_user_count
     *
     * @param receiveUserCount the value for t_message.receive_user_count
     *
     * @mbg.generated
     */
    public void setReceiveUserCount(Integer receiveUserCount) {
        this.receiveUserCount = receiveUserCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.read_count
     *
     * @return the value of t_message.read_count
     *
     * @mbg.generated
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.read_count
     *
     * @param readCount the value for t_message.read_count
     *
     * @mbg.generated
     */
    public void setReadCount(Integer readCount) {
        this.readCount = readCount;
    }
}