package com.xzs.pojo;

import com.baomidou.mybatisplus.annotation.TableField;

public class Tquestion {
    @TableField(exist = false)
    private String ShortTitle ;

    public String getShortTitle() {
        return ShortTitle;
    }

    public void setShortTitle(String shortTitle) {
        ShortTitle = shortTitle;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.question_type
     *
     * @mbg.generated
     */
    private Integer questionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.subject_id
     *
     * @mbg.generated
     */
    private Integer subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.grade_level
     *
     * @mbg.generated
     */
    private Integer gradeLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.difficult
     *
     * @mbg.generated
     */
    private Integer difficult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.correct
     *
     * @mbg.generated
     */
    private String correct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.info_text_content_id
     *
     * @mbg.generated
     */
    private String infoTextContentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.create_user
     *
     * @mbg.generated
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question
     *
     * @mbg.generated
     */
    public Tquestion(Integer id, Integer questionType, Integer subjectId, Integer score, Integer gradeLevel, Integer difficult, String correct, String infoTextContentId, Integer createUser, Integer status, String createTime, Boolean deleted) {
        this.id = id;
        this.questionType = questionType;
        this.subjectId = subjectId;
        this.score = score;
        this.gradeLevel = gradeLevel;
        this.difficult = difficult;
        this.correct = correct;
        this.infoTextContentId = infoTextContentId;
        this.createUser = createUser;
        this.status = status;
        this.createTime = createTime;
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question
     *
     * @mbg.generated
     */
    public Tquestion() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.id
     *
     * @return the value of t_question.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.id
     *
     * @param id the value for t_question.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.question_type
     *
     * @return the value of t_question.question_type
     *
     * @mbg.generated
     */
    public Integer getQuestionType() {
        return questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.question_type
     *
     * @param questionType the value for t_question.question_type
     *
     * @mbg.generated
     */
    public void setQuestionType(Integer questionType) {
        this.questionType = questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.subject_id
     *
     * @return the value of t_question.subject_id
     *
     * @mbg.generated
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.subject_id
     *
     * @param subjectId the value for t_question.subject_id
     *
     * @mbg.generated
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.score
     *
     * @return the value of t_question.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.score
     *
     * @param score the value for t_question.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.grade_level
     *
     * @return the value of t_question.grade_level
     *
     * @mbg.generated
     */
    public Integer getGradeLevel() {
        return gradeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.grade_level
     *
     * @param gradeLevel the value for t_question.grade_level
     *
     * @mbg.generated
     */
    public void setGradeLevel(Integer gradeLevel) {
        this.gradeLevel = gradeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.difficult
     *
     * @return the value of t_question.difficult
     *
     * @mbg.generated
     */
    public Integer getDifficult() {
        return difficult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.difficult
     *
     * @param difficult the value for t_question.difficult
     *
     * @mbg.generated
     */
    public void setDifficult(Integer difficult) {
        this.difficult = difficult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.correct
     *
     * @return the value of t_question.correct
     *
     * @mbg.generated
     */
    public String getCorrect() {
        return correct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.correct
     *
     * @param correct the value for t_question.correct
     *
     * @mbg.generated
     */
    public void setCorrect(String correct) {
        this.correct = correct == null ? null : correct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.info_text_content_id
     *
     * @return the value of t_question.info_text_content_id
     *
     * @mbg.generated
     */
    public String getInfoTextContentId() {
        return infoTextContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.info_text_content_id
     *
     * @param infoTextContentId the value for t_question.info_text_content_id
     *
     * @mbg.generated
     */
    public void setInfoTextContentId(String infoTextContentId) {
        this.infoTextContentId = infoTextContentId == null ? null : infoTextContentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.create_user
     *
     * @return the value of t_question.create_user
     *
     * @mbg.generated
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.create_user
     *
     * @param createUser the value for t_question.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.status
     *
     * @return the value of t_question.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.status
     *
     * @param status the value for t_question.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.create_time
     *
     * @return the value of t_question.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.create_time
     *
     * @param createTime the value for t_question.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.deleted
     *
     * @return the value of t_question.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.deleted
     *
     * @param deleted the value for t_question.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}