package com.xzs.pojo;

public class TSubject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subject.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subject.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subject.level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subject.level_name
     *
     * @mbg.generated
     */
    private String levelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subject.item_order
     *
     * @mbg.generated
     */
    private Integer itemOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subject.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated
     */
    public TSubject(Integer id, String name, Integer level, String levelName, Integer itemOrder, Boolean deleted) {
        this.id = id;
        this.name = name;
        this.level = level;
        this.levelName = levelName;
        this.itemOrder = itemOrder;
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated
     */
    public TSubject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subject.id
     *
     * @return the value of t_subject.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subject.id
     *
     * @param id the value for t_subject.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subject.name
     *
     * @return the value of t_subject.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subject.name
     *
     * @param name the value for t_subject.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subject.level
     *
     * @return the value of t_subject.level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subject.level
     *
     * @param level the value for t_subject.level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subject.level_name
     *
     * @return the value of t_subject.level_name
     *
     * @mbg.generated
     */
    public String getLevelName() {
        return levelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subject.level_name
     *
     * @param levelName the value for t_subject.level_name
     *
     * @mbg.generated
     */
    public void setLevelName(String levelName) {
        this.levelName = levelName == null ? null : levelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subject.item_order
     *
     * @return the value of t_subject.item_order
     *
     * @mbg.generated
     */
    public Integer getItemOrder() {
        return itemOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subject.item_order
     *
     * @param itemOrder the value for t_subject.item_order
     *
     * @mbg.generated
     */
    public void setItemOrder(Integer itemOrder) {
        this.itemOrder = itemOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subject.deleted
     *
     * @return the value of t_subject.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subject.deleted
     *
     * @param deleted the value for t_subject.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}