package com.xzs.mapper;

import com.xzs.pojo.TaskExam;
import com.xzs.pojo.TaskExamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TaskExamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam
     *
     * @mbg.generated
     */
    long countByExample(TaskExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam
     *
     * @mbg.generated
     */
    int deleteByExample(TaskExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam
     *
     * @mbg.generated
     */
    int insert(TaskExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam
     *
     * @mbg.generated
     */
    int insertSelective(TaskExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam
     *
     * @mbg.generated
     */
    List<TaskExam> selectByExampleWithRowbounds(TaskExamExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam
     *
     * @mbg.generated
     */
    List<TaskExam> selectByExample(TaskExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam
     *
     * @mbg.generated
     */
    TaskExam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TaskExam record, @Param("example") TaskExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TaskExam record, @Param("example") TaskExamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TaskExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TaskExam record);
}