package com.xzs.mapper;

import com.xzs.pojo.TaskExamCustomerAnswer;
import com.xzs.pojo.TaskExamCustomerAnswerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TaskExamCustomerAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam_customer_answer
     *
     * @mbg.generated
     */
    long countByExample(TaskExamCustomerAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam_customer_answer
     *
     * @mbg.generated
     */
    int deleteByExample(TaskExamCustomerAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam_customer_answer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam_customer_answer
     *
     * @mbg.generated
     */
    int insert(TaskExamCustomerAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam_customer_answer
     *
     * @mbg.generated
     */
    int insertSelective(TaskExamCustomerAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam_customer_answer
     *
     * @mbg.generated
     */
    List<TaskExamCustomerAnswer> selectByExampleWithRowbounds(TaskExamCustomerAnswerExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam_customer_answer
     *
     * @mbg.generated
     */
    List<TaskExamCustomerAnswer> selectByExample(TaskExamCustomerAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam_customer_answer
     *
     * @mbg.generated
     */
    TaskExamCustomerAnswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam_customer_answer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TaskExamCustomerAnswer record, @Param("example") TaskExamCustomerAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam_customer_answer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TaskExamCustomerAnswer record, @Param("example") TaskExamCustomerAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam_customer_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TaskExamCustomerAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_exam_customer_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TaskExamCustomerAnswer record);
}