package com.xzs.mapper;

import com.xzs.pojo.TExam_paperQuestionCustomerAnswer;
import com.xzs.pojo.TExam_paperQuestionCustomerAnswerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TExam_paperQuestionCustomerAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper_question_customer_answer
     *
     * @mbg.generated
     */
    long countByExample(TExam_paperQuestionCustomerAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper_question_customer_answer
     *
     * @mbg.generated
     */
    int deleteByExample(TExam_paperQuestionCustomerAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper_question_customer_answer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper_question_customer_answer
     *
     * @mbg.generated
     */
    int insert(TExam_paperQuestionCustomerAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper_question_customer_answer
     *
     * @mbg.generated
     */
    int insertSelective(TExam_paperQuestionCustomerAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper_question_customer_answer
     *
     * @mbg.generated
     */
    List<TExam_paperQuestionCustomerAnswer> selectByExampleWithRowbounds(TExam_paperQuestionCustomerAnswerExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper_question_customer_answer
     *
     * @mbg.generated
     */
    List<TExam_paperQuestionCustomerAnswer> selectByExample(TExam_paperQuestionCustomerAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper_question_customer_answer
     *
     * @mbg.generated
     */
    TExam_paperQuestionCustomerAnswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper_question_customer_answer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TExam_paperQuestionCustomerAnswer record, @Param("example") TExam_paperQuestionCustomerAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper_question_customer_answer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TExam_paperQuestionCustomerAnswer record, @Param("example") TExam_paperQuestionCustomerAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper_question_customer_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TExam_paperQuestionCustomerAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper_question_customer_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TExam_paperQuestionCustomerAnswer record);
}