package com.xzs.mapper;

import com.xzs.pojo.TexamPaper;
import com.xzs.pojo.TexamPaperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TexamPaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    long countByExample(TexamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    int deleteByExample(TexamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    int insert(TexamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    int insertSelective(TexamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    List<TexamPaper> selectByExampleWithRowbounds(TexamPaperExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    List<TexamPaper> selectByExample(TexamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    TexamPaper selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TexamPaper record, @Param("example") TexamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TexamPaper record, @Param("example") TexamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TexamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_paper
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TexamPaper record);

    void updateByExampleSelective(TexamPaper texamPaper);
}