package com.xzs.mapper;

import com.xzs.pojo.TextContent;
import com.xzs.pojo.TextContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TextContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_text_content
     *
     * @mbg.generated
     */
    long countByExample(TextContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_text_content
     *
     * @mbg.generated
     */
    int deleteByExample(TextContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_text_content
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_text_content
     *
     * @mbg.generated
     */
    int insert(TextContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_text_content
     *
     * @mbg.generated
     */
    int insertSelective(TextContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_text_content
     *
     * @mbg.generated
     */
    List<TextContent> selectByExampleWithBLOBsWithRowbounds(TextContentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_text_content
     *
     * @mbg.generated
     */
    List<TextContent> selectByExampleWithBLOBs(TextContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_text_content
     *
     * @mbg.generated
     */
    List<TextContent> selectByExampleWithRowbounds(TextContentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_text_content
     *
     * @mbg.generated
     */
    List<TextContent> selectByExample(TextContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_text_content
     *
     * @mbg.generated
     */
    TextContent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_text_content
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TextContent record, @Param("example") TextContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_text_content
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TextContent record, @Param("example") TextContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_text_content
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TextContent record, @Param("example") TextContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_text_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TextContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_text_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TextContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_text_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TextContent record);
}