package com.xzs.mapper;

import com.xzs.pojo.Tquestion;
import com.xzs.pojo.TquestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TquestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question
     *
     * @mbg.generated
     */
    long countByExample(TquestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question
     *
     * @mbg.generated
     */
    int deleteByExample(TquestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question
     *
     * @mbg.generated
     */
    int insert(Tquestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question
     *
     * @mbg.generated
     */
    int insertSelective(Tquestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question
     *
     * @mbg.generated
     */
    List<Tquestion> selectByExampleWithRowbounds(TquestionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question
     *
     * @mbg.generated
     */
    List<Tquestion> selectByExample(TquestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question
     *
     * @mbg.generated
     */
    Tquestion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Tquestion record, @Param("example") TquestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Tquestion record, @Param("example") TquestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Tquestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tquestion record);
}